[features]
seeds = false
skip-lint = false
[programs.localnet]
chatbids = "855UzS1Q9FPctVzgUzL8k4P7dT3aAdF3k7uoXDdWUvEV"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "Localnet"
wallet = "/Users/siddi_404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
