[features]
seeds = false
skip-lint = false
[programs.devnet]
chatbids = "ZzS7SCJrNP4qw7yjEM8WeKYNa1HtEPnFWokof6D5nku"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/Users/siddi_404/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
